name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ricardochaves/python-lint@v1.1.0
    - uses: stefanoeb/eslint-action@1.0.2
