#name: Lint

on: [pull_request, push]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: pip3 install flask --user
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: pip install black flake8

    #- name: Set up Node.js
    #  uses: actions/setup-node@v1
    #  with:
    #    node-version: 12

    # ESLint and Prettier must be in `package.json`
    #- name: Install Node.js dependencies
    #  run: npm install
      
    - name: Run Linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
       
        #JavaScript
        #eslint: true
        #prettier: true
        #eslint_extensions: js
        #prettier_extensions: js
        
  
        #Python
        black: true
        flake8: true
        black_extensions: py
        flake8_extensions: py
        
