name: CI

on: [pull_request]

jobs:

  stylelint:
    name: CSS Linter (stylelint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install stylelint stylelint-config-recommended

      - name: Run StyleLint
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_input: '**/*.css'

  eslint:
    name: JS Linter (eslint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install eslint

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

  flake8_lint:
    name: Python Linters (flake8)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: pip3 install flask --user

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: pip install flake8

    - name: Run Linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        flake8: true
        flake8_extensions: py
        flake8_args: "--ignore=E301,E302,E303,E401,E501,E127,E128"
